In [1]:
from game import *
g = game()

In [3]:
key = 2
g.move(key)

In [2]:
x=np.array(g.visualize())
print(x.T)
print('food : ', g.food,'\nhead : ',g.head, '\nbody : ',g.body)
print('state : ', g.get_state())

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class DQN(nn.Module):
    def __init__(self, state_size, action_size):
        super(DQN, self).__init__()
        self.fc1 = nn.Linear(state_size, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, action_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
agent = DQN(9,4)
agent.load_state_dict(torch.load('dqn_model_230.pth'))
q_values = agent(torch.FloatTensor(g.get_state()))
action = torch.argmax(q_values).item()
agent

DQN(
  (fc1): Linear(in_features=9, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=4, bias=True)
)

In [4]:
torch.from_numpy(g.get_state())

tensor([ 0.,  1.,  0.,  1.,  1.,  0.,  0.,  0., 13.], dtype=torch.float64)

In [3]:
import torch
x=torch.load('dqn_model_286small.pth')

In [6]:
import numpy as np
from game import *
g = game()
def to_numpy(x,dic):
    fc = x[dic].to(torch.device("cpu"))
    fc = fc.numpy()
    return fc
def action(state):
    result = np.matmul(fc1,np.array(state))
    result = result+b1
    result = np.maximum(result, 0)   # Apply ReLU activation function
    result = np.matmul(fc2,result)
    result = result+b2
    result = np.maximum(result, 0)   # Apply ReLU activation function
    result = np.matmul(fc3,result)
    result = result+b3
    return result
fc1 = np.load('fc1.npy')
fc2 = np.load('fc2.npy')
fc3 = np.load('fc3.npy')
b1 = np.load('b1.npy')
b2 = np.load('b2.npy')
b3 = np.load('b3.npy')
state = g.get_state()

In [6]:
# g.move(np.argmax(action(state)))
print(g.visualize().T)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [7]:
np.argmax(action(g.get_state()))

2

In [8]:
action(g.get_state())

array([-0.85148166,  2.29998679,  2.39747466,  1.99006445])

In [9]:
agent(torch.FloatTensor(g.get_state()))

tensor([-0.8515,  2.3000,  2.3975,  1.9901], grad_fn=<AddBackward0>)

In [24]:
torch.argmax(agent(torch.FloatTensor(g.get_state())))

tensor(1)

In [37]:
b3

array([0.31632835, 0.25919864, 0.18016426, 0.38999352], dtype=float32)

In [32]:
agent.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.3722, -0.5413, -0.0090,  ...,  0.0225,  0.2799,  0.0574],
                      [-0.3022, -0.2873,  0.2645,  ...,  0.4173, -0.1135, -0.0721],
                      [ 0.2956,  0.2769, -0.1359,  ...,  0.1556,  0.5216, -0.0144],
                      ...,
                      [ 0.2600, -0.0628,  0.2948,  ..., -0.1818, -0.0565, -0.2484],
                      [-0.0159,  0.4283, -0.1894,  ...,  0.1432, -0.3145, -0.0436],
                      [-0.1565,  0.1787,  0.1698,  ..., -0.2575, -0.3051, -0.0182]])),
             ('fc1.bias',
              tensor([-0.0877,  0.3203, -0.2253, -0.2265,  0.2732, -0.2570, -0.2585,  0.2055,
                      -0.1632, -0.0460,  0.6006, -0.3830,  0.3834,  0.2731,  0.0620,  0.1483,
                      -0.3338,  0.2284, -0.1604, -0.0387, -0.2606, -0.1789, -0.3317, -0.0432,
                       0.2589,  0.0572, -0.4772,  0.1687, -0.0603,  0.1326, -0.2894, -0.0435,
                      -0.4802, -0.39

In [8]:
np.save('fc1',fc1)
np.save('b1',b1)
np.save('fc2',fc2)
np.save('b2',b2)
np.save('fc3',fc3)
np.save('b3',b3)

In [7]:
b1 = to_numpy(x,'fc1.bias')
fc1 =to_numpy(x,'fc1.weight')
b2 = to_numpy(x,'fc2.bias')
fc2 =to_numpy(x,'fc2.weight')
b3 = to_numpy(x,'fc3.bias')
fc3 =to_numpy(x,'fc3.weight')

In [42]:
text_file = open("fc1.npy", "r")
lines = text_file.readlines()
print(lines)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

In [15]:
b3

array([0.08725061, 0.18133354, 0.81122863, 0.4002299 ], dtype=float32)